### ISSUE TITLE
7.0.1 Fails to resolve after installing Hotfix 6167 on AEM 6.0

### ISSUE THREAD

**Issue by steven-walters** [Citytechinc/cq-groovy-console#41]
We've encountered an issue where groovy console 7.0.1 fails to resolve after the installation of Hotfix 6167 on AEM 6.0

The reason we found for the failure is that that there is an update to the cq-wcm-taglib package (to version 5.7.10) that bumps the "com.day.cq.wcm.tags" package from "5.7.0" to "6.0.0".  this causes the  version range that is generated by bnd on the build of "[5.7,6.0)" to fail.

There are other Adobe bundles that refer to this package without an associated version range, so this is inclining that groovy console should likely not also be restricted to the version.
We've locally made a change to the `maven-bundle-plugin` section to support this:
`<Import-Package>com.day.cq.wcm.tags;version=!,*</Import-Package>`

We're not sure completely sure how to proceed further on providing this alteration for 6.0, since master and develop have both updated to AEM 6.1

**Comment by JEBailey** [comment]
We've experienced the same failure on 6.1. The provided solution resolved the problem.

**Comment by lykorian** [comment]
Unfortunately, these issues may occur from time after installation of hotfixes and service packs, since this affects the dependency versions for the bundles inherited from our parent Maven pom file.  Glad you got it working.

**Comment by pdoddamani** [comment]
Thanks steven you saved my day
