### ISSUE TITLE
8.0.0 does not work with latest hotfixes on 6.1

### ISSUE THREAD

**Issue by gruberroland-netcentric** [Citytechinc/cq-groovy-console#45]
Adobe changed the version of com.day.cq.wcm.tags to 6. Please update version range.

com.day.cq.wcm.tags,version=[5.7,6) -- Cannot be resolved

**Comment by lykorian** [comment]
Which hotfixes and/or service packs are you using?  I was unable to find one containing the version you mentioned.

**Comment by gruberroland-netcentric** [comment]
It happens on 6.1 with service pack 1 and the following additional hotfixes: 
* 9336
* 9436
* 9504
* 9760
* 9384
* 10936

There I get com.day.cq.wcm.tags,version=6.0.0 for bundle com.day.cq.wcm.cq-wcm-taglib (bundle version 5.8.2).

**Comment by d-wells** [comment]
This is also true for Adobe 6.1 Service Pack 1.  One of the following hot-fixes introduced this problem with Groovy Console 7.0.2. and is still true in the 8.x version:

cq-6.1.0-hotfix-11493 (version 1.0)
cq-6.1.0-hotfix-10768 (version 1.4)
cq-6.1.0-hotfix-8867 (version 1.1)

8867 version 1.1 isn't available on package share (at least not last time I checked), so I've attached it.  It's possible that 11493 is also not available on package share either, so if you need that, you can let me know, and I'll attach it as well.
[cq-6.1.0-hotfix-8867-1.1.zip](https://github.com/Citytechinc/cq-groovy-console/files/366093/cq-6.1.0-hotfix-8867-1.1.zip)

**Comment by lykorian** [comment]
Sure, can you go ahead and attach 11493?

**Comment by d-wells** [comment]
[cq-6.1.0-hotfix-11493-1.0.zip](https://github.com/Citytechinc/cq-groovy-console/files/366379/cq-6.1.0-hotfix-11493-1.0.zip)
