### ISSUE TITLE
Dead documentation link in Groovy Console 7

### ISSUE THREAD

**Issue by toniedzwiedz** [Citytechinc/cq-groovy-console#46]
![dead link](https://cloud.githubusercontent.com/assets/8336085/17862796/c058978e-688e-11e6-960d-b57beb3ccb62.png)

There's a useful link in version 7 (and possibly others) of the Groovy Console that has gone dead.

`http://code.citytechinc.com/aem-groovy-extension/groovydocs/com/citytechinc/aem/groovy/extension/services/impl/DefaultMetaClassExtensionProvider.html`

When clicked, it takes me to http://www.digitalatolson.com/open-source

Can you do a release of a version compatible with AEM 6.0 that links to the current docs (or simply inlines them as it once used to)? Or maybe set up redirects taking one to an equivalent page on your new website?

**Comment by lykorian** [comment]
Fixed in 9.0.1 - thanks.

https://github.com/Citytechinc/cq-groovy-console/releases/tag/9.0.1

**Comment by lykorian** [comment]
The direct link: http://code.digitalatolson.com/aem-groovy-extension/groovydocs/com/citytechinc/aem/groovy/extension/services/impl/DefaultMetaClassExtensionProvider.html

**Comment by toniedzwiedz** [comment]
@lykorian is Version 9.0.1 compatible with AEM 6.0?

**Comment by lykorian** [comment]
No, it is not.  Updating past versions with non-critical fixes is lower priority... I will try to fix it soon, though.

**Comment by lykorian** [comment]
Versions 7 and 8 have new hotfix releases now.  Thanks.

**Comment by toniedzwiedz** [comment]
@lykorian I think the link went dead again. http://code.digitalatolson.com/aem-groovy-extension/groovydocs/com/citytechinc/aem/groovy/extension/services/impl/DefaultMetaClassExtensionProvider.html gives me a 404

**Comment by lykorian** [comment]
OK, it's back now.  Thanks.
