### ISSUE TITLE
Groovy Console does not install under AEM 6.1 SP2

### ISSUE THREAD

**Issue by JBodkin** [Citytechinc/cq-groovy-console#47]
The latest service pack for AEM 6.1 introduces an new version of the tag api and hence the installation fails.

com.day.cq.wcm.tags,version=[5.7,6) -- Cannot be resolved

The version exported by the /system/console has been increased.

com.day.cq.wcm.tags,version=6.0.0

**Comment by JBodkin** [comment]
The dependency that seems to be the issue is:

```
<dependency>
    <groupId>com.day.cq.wcm</groupId>
    <artifactId>cq-wcm-taglib</artifactId>
    <version>[5.7.4,5.8.2]</version>
</dependency>
```

**Comment by toniedzwiedz** [comment]
Looks the same as https://github.com/Citytechinc/cq-groovy-console/issues/45

**Comment by lykorian** [comment]
This was already fixed in 8.0.2.

**Comment by JBodkin** [comment]
Turns out I was downloading the old version and not the newer version!

**Comment by lykorian** [comment]
Great, glad that worked.
